services:
  telegram-bot:
    build: .
    container_name: telgram-sentinel-bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      GROUP_ID: ${GROUP_ID}
      CHECK_HOUR: ${CHECK_HOUR}
      CHECK_MINUTE: ${CHECK_MINUTE}